# Site settings
title: Ryan Chae's Blog
description: > # this means to ignore newlines until "baseurl:"
  A blog by Ryan Chae about data science, machine learning, and data visualiation.
baseurl:  # the subpath of your site, e.g. /blog/
url:  "http://ryanchae.com/"
github_username:  chae1108

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"
